---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: session-database
  labels:
    app: alertmanager
    component: monitoring
spec:
  selector:
    app: alertmanager
    component: monitoring
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      protocol: TCP
  type: ClusterIP
