---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: session-database
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
    component: monitoring
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
