---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: session-database
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter:9121']
        metrics_path: /metrics
        scrape_interval: 10s

      - job_name: 'session-database'
        static_configs:
          - targets: ['session-database-service:8080']
        metrics_path: /metrics
        scrape_interval: 30s
