---
version: '3.8'

services:
  session-database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: session-database
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
