---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
  namespace: session-database
  labels:
    app: grafana
    component: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: grafana
      component: monitoring
