---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: session-database
  labels:
    app: prometheus
    component: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus
      component: monitoring
