---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-database-sa
  namespace: session-database
  labels:
    app: session-database
    component: security
automountServiceAccountToken: false
