---
apiVersion: batch/v1
kind: Job
metadata:
  name: tls-cert-generator
  namespace: session-database
  labels:
    app: tls-cert-generator
    component: security
spec:
  template:
    metadata:
      labels:
        app: tls-cert-generator
        component: security
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cert-generator
          image: alpine/openssl:3.3.0@sha256:b85f81fdb4c7ac8e88fb9c2a0bc0daaf946e4a76bdb6f9fe5b9c42b7ee3a4b68
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"
          command:
            - /bin/sh
            - /scripts/generate-certs.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: tls-certs
              mountPath: /tls
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: scripts
          configMap:
            name: redis-tls-config
            defaultMode: 0755
        - name: tls-certs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
