---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-lua-init
  namespace: session-database
  labels:
    app: session-database
    component: initialization
  annotations:
    # Ignore kube-score warnings for Redis user compatibility and development setup
    kube-score/ignore: container-security-context-user-group-id,container-image-tag,container-image-pull-policy
spec:
  template:
    metadata:
      labels:
        app: session-database
        component: initialization
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - name: redis-init
          image: session-database:latest
          imagePullPolicy: Never
          command: ["/usr/local/bin/init-lua-scripts.sh"]
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: session-database-secret
                  key: redis-password
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "200Mi"
      volumes:
        - name: tmp-volume
          emptyDir: {}
  backoffLimit: 3
