---
apiVersion: v1
kind: Service
metadata:
  name: session-database-service
  namespace: session-database
spec:
  selector:
    app: session-database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
