---
apiVersion: v1
kind: ConfigMap
metadata:
  name: session-database-config
  namespace: session-database
data:
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  SESSION_TTL_SECONDS: "3600"
  MAX_SESSIONS_PER_USER: "5"
  CLEANUP_INTERVAL_SECONDS: "300"
  LOG_LEVEL: "INFO"
