---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-database
  namespace: session-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-database
  template:
    metadata:
      labels:
        app: session-database
    spec:
      containers:
        - name: session-database
          image: session-database:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: REDIS_DB
            - name: SESSION_TTL_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: SESSION_TTL_SECONDS
            - name: MAX_SESSIONS_PER_USER
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: MAX_SESSIONS_PER_USER
            - name: CLEANUP_INTERVAL_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: CLEANUP_INTERVAL_SECONDS
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: LOG_LEVEL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: session-database-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - mountPath: /data
              name: redis-storage
            - mountPath: /logs
              name: redis-logs
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: session-database-pvc
        - name: redis-logs
          emptyDir: {}
