---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-database-pvc
  namespace: session-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
