---
apiVersion: v1
kind: Secret
metadata:
  name: session-database-secret
  namespace: session-database
  labels:
    app: session-database
type: Opaque
stringData:
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
