---
name: Feature Request
description: Suggest a new feature or enhancement for the session database service
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please provide detailed information below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which component would this feature affect?
      options:
        - Redis Master/Replica
        - Sentinel HA Setup
        - Session Management
        - Monitoring/Observability
        - Alerting
        - Kubernetes Deployment
        - Helm Chart
        - Scripts/Automation
        - Documentation
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High - Critical for production use
        - Medium - Important for functionality
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: How would you use this feature? What problem does it solve for you?
    validations:
      required: true

  - type: textarea
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      placeholder: Describe any breaking changes and migration path

  - type: checkboxes
    id: security
    attributes:
      label: Security Implications
      description: Does this feature have security implications?
      options:
        - label: This feature may have security implications
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Any additional information that might help

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all relevant information
          required: true
