---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-exporter-service
  namespace: session-database
  labels:
    app: redis-cache-exporter
    component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: redis-cache-exporter
    component: monitoring
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121
      protocol: TCP
  type: ClusterIP
