---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: session-database
  labels:
    app: redis-exporter
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
      component: monitoring
  template:
    metadata:
      labels:
        app: redis-exporter
        component: monitoring
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis-exporter
                topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.58.0@sha256:b7c9b6c2c60ea2bd45f88b1e38a6077cb19ed17d59e0b8c7a48e7ad82a51c5c1
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 9121
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"
          env:
            - name: REDIS_ADDR
              value: "redis://session-database-service:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: session-database-secret
                  key: REDIS_PASSWORD
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: REDIS_DB
            - name: CACHE_DB
              valueFrom:
                configMapKeyRef:
                  name: session-database-config
                  key: CACHE_DB
          args:
            - --redis.addr=$(REDIS_ADDR)
            - --redis.password=$(REDIS_PASSWORD)
            - --web.listen-address=:9121
            - --namespace=redis
            - --log-format=json
            - --include-system-metrics=true
            - --redis.db=$(REDIS_DB)
            - --check-keys=session:*,user_sessions:*,refresh_token:*,deletion_token:*
            - --check-single-keys=session_stats,session_config,session_cleanup
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            tcpSocket:
              port: 9121
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: tmp
          emptyDir: {}
