---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: session-database-project
  namespace: argocd
  labels:
    project: session-database
spec:
  description: Session Database Project

  sourceRepos:
    - 'https://github.com/Recipe-Web-App/session-database.git'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://prometheus-community.github.io/helm-charts'

  destinations:
    - namespace: session-database
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: MutatingAdmissionWebhook
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingAdmissionWebhook

  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: 'batch'
      kind: Job
    - group: 'batch'
      kind: CronJob
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
    - group: 'monitoring.coreos.com'
      kind: PrometheusRule

  roles:
    - name: admin
      description: Admin access to session database project
      policies:
        - p, proj:session-database-project:admin, applications, *,
          session-database-project/*, allow
        - p, proj:session-database-project:admin, repositories, *, *, allow
        - p, proj:session-database-project:admin, certificates, *, *, allow
      groups:
        - session-database:admin

    - name: developer
      description: Developer access to session database project
      policies:
        - p, proj:session-database-project:developer, applications, get,
          session-database-project/*, allow
        - p, proj:session-database-project:developer, applications, sync,
          session-database-project/*, allow
        - p, proj:session-database-project:developer, applications,
          action/*, session-database-project/*, allow
        - p, proj:session-database-project:developer, repositories, get, *, allow
      groups:
        - session-database:developer
