---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: session-database-project
  namespace: argocd
  labels:
    app.kubernetes.io/name: session-database-project
spec:
  description: Session Database Project
  sourceRepos:
    - '${GITHUB_REPO_URL}'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://prometheus-community.github.io/helm-charts'
  destinations:
    - namespace: session-database
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
    - group: 'storage.k8s.io'
      kind: StorageClass
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'policy'
      kind: PodSecurityPolicy
    - group: 'security.istio.io'
      kind: PeerAuthentication
    - group: 'security.istio.io'
      kind: AuthorizationPolicy
    - group: 'networking.istio.io'
      kind: DestinationRule
    - group: 'networking.istio.io'
      kind: ServiceEntry
    - group: 'networking.istio.io'
      kind: VirtualService
    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
    - group: 'monitoring.coreos.com'
      kind: PrometheusRule
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Service
    - group: ''
      kind: Secret
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: 'batch'
      kind: Job
    - group: 'batch'
      kind: CronJob
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget
  roles:
    - name: admin
      description: Admin role for session-database project
      policies:
        - p, proj:session-database-project:admin, applications, *,
          proj:session-database-project/*, allow
        - p, proj:session-database-project:admin, repositories, *, *, allow
        - p, proj:session-database-project:admin, certificates, *, *, allow
      groups:
        - session-database:admin
