---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: session-database
  namespace: argocd
  labels:
    app.kubernetes.io/name: session-database
    app.kubernetes.io/instance: session-database
spec:
  project: session-database-project
  source:
    repoURL: ${GITHUB_REPO_URL}
    targetRevision: main
    path: helm/session-database
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: session-database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
