---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: session-cleanup
  namespace: session-database
  labels:
    app: session-cleanup
    component: maintenance
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app: session-cleanup
            component: maintenance
        spec:
          serviceAccountName: session-cleanup
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: session-cleanup
              image: redis:8.0-alpine@sha256:8c5ebd8e39ac3cfb85b4583dcd5f8b6b4c7b2da0c9f394b8e4aa52b7b2b8b6b7
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "10m"
                  ephemeral-storage: "500Mi"
                limits:
                  memory: "64Mi"
                  cpu: "50m"
                  ephemeral-storage: "1Gi"
              env:
                - name: REDIS_HOST
                  value: "session-database-service"
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: session-database-secret
                      key: redis-password
                - name: CLEANUP_BATCH_SIZE
                  value: "100"
                - name: MAX_EXECUTION_TIME
                  value: "30"
              command:
                - /scripts/jobHelpers/session-cleanup.sh
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
