---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-sentinel-pdb
  namespace: session-database
  labels:
    app: redis-sentinel
    component: ha
spec:
  selector:
    matchLabels:
      app: redis-sentinel
      component: ha
  minAvailable: 2  # Need at least 2 for quorum
